# Generated by Django 2.2.28 on 2026-03-11 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('AI', 'AI'), ('NOTE', 'Note Taking'), ('FLASH', 'Flashcard'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('link', models.URLField()),
                ('score', models.FloatField(default=0.0)),
                ('slug', models.SlugField(unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdtools', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likedtools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
