# Generated by Django 2.2.28 on 2026-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.TextField(max_length=2000),
        ),
    ]
